language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3

os: linux

matrix:
  include:
    - os: osx
      language: generic

install:
  - pip install -e .
  - pip install -r dev_requirements.txt
  - python setup.py build install

script:
  - make
